#!/bin/bash

function block() {
# Basic functions from URL
source <(curl -s https://raw.githubusercontent.com/CPITMschool/Scripts/main/utils.sh)

while true; do
    response=$(curl -s -X POST http://localhost:5678 \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"zgs_getStatus","params":[],"id":1}')
    
    logSyncHeight=$(jq -r '.result.logSyncHeight' <<< "$response")
    connectedPeers=$(jq -r '.result.connectedPeers' <<< "$response")
    
    echo -e "logSyncHeight: \033[32m$logSyncHeight\033[0m, connectedPeers: \033[34m$connectedPeers\033[0m"
    sleep 5
done
block
